import turtle

screen = turtle.Screen()
screen.bgcolor('black')
pen = turtle.Turtle()
pen.color('red')
pen.fillcolor('red')
pen.pensize(3)
pen.penup()
pen.goto(0,-100)
pen.pendown()
pen.begin_fill()
pen.left(140)
pen.forward(180)
pen.circle(-90,200)
pen.left(120)
pen.circle(-90,200)
pen.forward(180)
pen.end_fill()
pen.penup()
pen.goto(-15,0)
pen.pendown()
pen.color('black')
pen.write('Nawaf',align='center', font=('Arial', 45,'normal'))
pen.hideturtle()
screen.exitonclick()